# Generated by Django 6.0.1 on 2026-02-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0003_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.CharField(default="Default Supplier", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="current_stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
